import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Try loading .env if not already in process.env
const __dirname = path.dirname(fileURLToPath(import.meta.url));
for (const envPath of [
  path.resolve(__dirname, "../../../.env"),
  path.resolve(__dirname, "../.env"),
  path.resolve(process.cwd(), ".env"),
]) {
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, "utf8").split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#")) {
        const [k, ...v] = trimmed.split("=");
        if (k && !process.env[k.trim()]) {
          process.env[k.trim()] = v.join("=").trim().replace(/^["']|["']$/g, "");
        }
      }
    }
  }
}

import { db, officersTable, casesTable, alertsTable, investigationNotesTable, initDb } from "./index.js";
import { eq } from "drizzle-orm";


interface CaseSeedData {
  firNo: string;
  policeStation: string;
  date: string;
  victimName: string;
  victimContact: string;
  victimEmail: string;
  suspectedWalletAddress: string;
  txHash: string;
  cryptoType: string;
  amountLost: string;
  exchangeName: string;
  telegramId?: string;
  websiteUrl?: string;
  suspectMobile?: string;
  socialMediaHandle?: string;
  ipAddress?: string;
  bankDetails?: string;
  blockchainNetwork: string;
  screenshotsCollected: boolean;
  evidenceAttached: boolean;
  remarks: string;
  status: "open" | "under_investigation" | "closed" | "frozen" | "escalated";
  notes?: string[];
}

// Reusable syndicate entities for clustering
const SYNDICATE_WALLETS = {
  GOLDEN_DRAGON_USDT: "TX7N2sK9wQ8R1pL3mE4vY5xZ6tU8jM2aK1", // 6 linked cases (Tron TRC-20)
  PHISHING_DEX_ETH: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e", // 5 linked cases (Ethereum ERC-20)
  PIG_BUTCHERING_BTC: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa", // 4 linked cases (Bitcoin)
  TASK_SCAM_SOL: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM", // 4 linked cases (Solana)
  ARBITRAGE_BNB: "0x55d398326f99059fF775485246999027B3197955", // 3 linked cases (BNB Chain)
  TELEGRAM_VIP_TRC20: "TYDnyT8STPGcD3Y6A58G5n9pP5sM1aR2bK", // 3 linked cases (Tron TRC-20)
};

const SYNDICATE_TELEGRAMS = {
  CRYPTO_VIP: "@crypto_vip_signal_in",
  FX_TRADER: "@fx_global_trader_raj",
  BINANCE_CLAIM: "@binance_airdrop_bot_india",
  TASK_ADMIN: "@task_earning_admin_vip",
  PIG_BUTCHERING: "@lucy_crypto_analyst",
};

const SYNDICATE_MOBILES = {
  MOB_1: "+91 98765 43210",
  MOB_2: "+91 91234 56789",
  MOB_3: "+91 88821 99012",
  MOB_4: "+91 97110 84321",
};

const SYNDICATE_WEBSITES = {
  BITGET_PHISH: "https://bitget-trade-in.vip",
  TASK_EARN: "https://coin-earn-task99.top",
  TETHER_MINE: "https://tether-mining-pro.cc",
  CLAIM_AIRDROP: "https://binance-bonus-claim.xyz",
  QUANT_BOT: "https://ai-quant-yield-defi.org",
};

const dummyCases: CaseSeedData[] = [
  // Cluster 1: Golden Dragon TRC20 USDT Syndicate (6 cases)
  {
    firNo: "FIR-2024-DEL-0101",
    policeStation: "Cyber Crime Cell New Delhi",
    date: "2024-01-12",
    victimName: "Aarav Sharma",
    victimContact: "+91 98101 23456",
    victimEmail: "aarav.sharma91@gmail.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.GOLDEN_DRAGON_USDT,
    txHash: "9a8f3b2c1d0e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a",
    cryptoType: "USDT",
    amountLost: "450000.00",
    exchangeName: "WazirX",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: SYNDICATE_WEBSITES.TETHER_MINE,
    suspectMobile: SYNDICATE_MOBILES.MOB_1,
    socialMediaHandle: "t.me/crypto_vip_signal_in",
    ipAddress: "103.212.43.19",
    bankDetails: "HDFC Bank A/C: 50100234918231, IFSC: HDFC0000128",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim lured into high-yield USDT liquidity mining pool promising 8% daily returns.",
    status: "under_investigation",
    notes: [
      "Section 91 CrPC notice dispatched to WazirX and Tether Ltd regarding blacklisting of wallet.",
      "IP tracing logs indicate VPN exit node based in Southeast Asia.",
    ],
  },
  {
    firNo: "FIR-2024-MUM-0142",
    policeStation: "Cyber Crime Police Station BKC Mumbai",
    date: "2024-01-20",
    victimName: "Rohan Kulkarni",
    victimContact: "+91 98203 87462",
    victimEmail: "rohan.kulkarni@techcorp.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.GOLDEN_DRAGON_USDT,
    txHash: "3f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e",
    cryptoType: "USDT",
    amountLost: "1250000.00",
    exchangeName: "Binance",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: SYNDICATE_WEBSITES.TETHER_MINE,
    suspectMobile: SYNDICATE_MOBILES.MOB_1,
    socialMediaHandle: "instagram.com/crypto_expert_rajesh",
    ipAddress: "103.212.43.22",
    bankDetails: "ICICI Bank A/C: 001105023912, IFSC: ICIC0000011",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Part of Golden Dragon Syndicate. Funds routed through Huobi and OKX deposit addresses.",
    status: "escalated",
    notes: [
      "Linked to FIR-2024-DEL-0101 via identical wallet and Telegram ID.",
      "Letter of Request initiated through Interpol NCB for Binance exchange records.",
    ],
  },
  {
    firNo: "FIR-2024-BLR-0219",
    policeStation: "Cyber Crime Police Station Bengaluru South",
    date: "2024-02-05",
    victimName: "Sneha Ramanathan",
    victimContact: "+91 94480 11928",
    victimEmail: "sneha.raman@fintechsol.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.GOLDEN_DRAGON_USDT,
    txHash: "7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a",
    cryptoType: "USDT",
    amountLost: "890000.00",
    exchangeName: "CoinDCX",
    telegramId: SYNDICATE_TELEGRAMS.TASK_ADMIN,
    websiteUrl: SYNDICATE_WEBSITES.TETHER_MINE,
    suspectMobile: SYNDICATE_MOBILES.MOB_1,
    socialMediaHandle: "t.me/task_earning_admin_vip",
    ipAddress: "185.220.101.5",
    bankDetails: "Axis Bank A/C: 918020045192834, IFSC: UTIB0000045",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim instructed to buy USDT on CoinDCX and transfer to syndicate smart contract.",
    status: "under_investigation",
    notes: [
      "Axis Bank account frozen with lien of ₹4,20,000 under Section 102 CrPC.",
    ],
  },
  {
    firNo: "FIR-2024-HYD-0304",
    policeStation: "Cyber Crime Police Station Cyberabad",
    date: "2024-02-18",
    victimName: "Vikram Reddy",
    victimContact: "+91 98490 55431",
    victimEmail: "v.reddy@hyderabadit.org",
    suspectedWalletAddress: SYNDICATE_WALLETS.GOLDEN_DRAGON_USDT,
    txHash: "1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f",
    cryptoType: "USDT",
    amountLost: "2100000.00",
    exchangeName: "Binance",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: SYNDICATE_WEBSITES.TETHER_MINE,
    suspectMobile: SYNDICATE_MOBILES.MOB_2,
    socialMediaHandle: "whatsapp.com/channel/0029VaCryptoSignals",
    ipAddress: "103.212.43.30",
    bankDetails: "State Bank of India A/C: 38921049281, IFSC: SBIN0001234",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "High-value corporate victim duped under pretext of institutional crypto staking.",
    status: "open",
    notes: [
      "Wallet flagged as Critical Risk level on Chainalysis and MistTrack.",
    ],
  },
  {
    firNo: "FIR-2024-PUN-0388",
    policeStation: "Cyber Crime Police Station Shivajinagar Pune",
    date: "2024-03-02",
    victimName: "Meera Deshmukh",
    victimContact: "+91 97654 32189",
    victimEmail: "meera.deshmukh@gmail.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.GOLDEN_DRAGON_USDT,
    txHash: "5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b",
    cryptoType: "USDT",
    amountLost: "350000.00",
    exchangeName: "ZebPay",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: SYNDICATE_WEBSITES.TETHER_MINE,
    suspectMobile: SYNDICATE_MOBILES.MOB_1,
    socialMediaHandle: "t.me/crypto_vip_signal_in",
    ipAddress: "103.212.43.19",
    bankDetails: "Kotak Mahindra Bank A/C: 8412940219, IFSC: KKBK0000958",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Part of Golden Dragon network. Multiple complaints lodged nationwide.",
    status: "under_investigation",
    notes: [
      "Coordinating with Delhi and Mumbai Cyber Cells for joint syndicate takedown.",
    ],
  },
  {
    firNo: "FIR-2024-GGN-0450",
    policeStation: "Cyber Crime Police Station East Gurugram",
    date: "2024-03-15",
    victimName: "Karan Malhotra",
    victimContact: "+91 99112 33445",
    victimEmail: "karan.m@investcorp.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.GOLDEN_DRAGON_USDT,
    txHash: "8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d",
    cryptoType: "USDT",
    amountLost: "1750000.00",
    exchangeName: "Bybit",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: SYNDICATE_WEBSITES.TETHER_MINE,
    suspectMobile: SYNDICATE_MOBILES.MOB_1,
    socialMediaHandle: "t.me/crypto_vip_signal_in",
    ipAddress: "103.212.43.25",
    bankDetails: "Punjab National Bank A/C: 198200150029381, IFSC: PUNB0198200",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Sixth linked case with Golden Dragon TRC20 wallet. Cumulative loss exceeding ₹68 Lakhs.",
    status: "frozen",
    notes: [
      "Wallet marked as Frozen by overseas exchange following mutual legal assistance request.",
    ],
  },

  // Cluster 2: Phishing DEX Ethereum Smart Contract Drainer (5 cases)
  {
    firNo: "FIR-2024-DEL-0210",
    policeStation: "Cyber Crime Cell South Delhi",
    date: "2024-01-25",
    victimName: "Ananya Sen",
    victimContact: "+91 98118 76543",
    victimEmail: "ananya.sen@designstudio.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.PHISHING_DEX_ETH,
    txHash: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
    cryptoType: "ETH",
    amountLost: "620000.00",
    exchangeName: "MetaMask / Uniswap Phish",
    telegramId: SYNDICATE_TELEGRAMS.BINANCE_CLAIM,
    websiteUrl: SYNDICATE_WEBSITES.CLAIM_AIRDROP,
    suspectMobile: SYNDICATE_MOBILES.MOB_3,
    socialMediaHandle: "twitter.com/BinanceAirdropIN",
    ipAddress: "194.26.29.112",
    bankDetails: null,
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim clicked fraudulent airdrop link that executed Permit2 approve drainage transaction.",
    status: "under_investigation",
    notes: [
      "Malicious smart contract analyzed. Unlimited allowance granted to drainer contract.",
    ],
  },
  {
    firNo: "FIR-2024-MUM-0299",
    policeStation: "Cyber Crime Cell Bandra Kurla Complex Mumbai",
    date: "2024-02-10",
    victimName: "Aditya Singhania",
    victimContact: "+91 98201 44556",
    victimEmail: "aditya.singhania@mumbaicapital.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.PHISHING_DEX_ETH,
    txHash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
    cryptoType: "ETH",
    amountLost: "1480000.00",
    exchangeName: "Uniswap Phishing Clone",
    telegramId: SYNDICATE_TELEGRAMS.BINANCE_CLAIM,
    websiteUrl: SYNDICATE_WEBSITES.CLAIM_AIRDROP,
    suspectMobile: SYNDICATE_MOBILES.MOB_3,
    socialMediaHandle: "t.me/binance_airdrop_bot_india",
    ipAddress: "194.26.29.115",
    bankDetails: null,
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Drained 5.2 ETH via malicious permit signature.",
    status: "open",
    notes: [
      "Funds forwarded to Tornado.Cash mixer in 1.0 ETH chunks.",
    ],
  },
  {
    firNo: "FIR-2024-BLR-0382",
    policeStation: "Cyber Crime Cell Whitefield Bengaluru",
    date: "2024-02-28",
    victimName: "Prateek Sundaram",
    victimContact: "+91 99805 12390",
    victimEmail: "prateek.sundaram@cloudtech.io",
    suspectedWalletAddress: SYNDICATE_WALLETS.PHISHING_DEX_ETH,
    txHash: "0x7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456",
    cryptoType: "ETH",
    amountLost: "950000.00",
    exchangeName: "MetaMask Web3",
    telegramId: SYNDICATE_TELEGRAMS.BINANCE_CLAIM,
    websiteUrl: SYNDICATE_WEBSITES.CLAIM_AIRDROP,
    suspectMobile: SYNDICATE_MOBILES.MOB_3,
    socialMediaHandle: "t.me/binance_airdrop_bot_india",
    ipAddress: "194.26.29.112",
    bankDetails: null,
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Drainer identified across multiple Bengaluru tech park employees.",
    status: "under_investigation",
    notes: [
      "Domain registrar Namecheap contacted for registrant KYC and domain suspension.",
    ],
  },
  {
    firNo: "FIR-2024-KOL-0195",
    policeStation: "Cyber Crime PS Lalbazar Kolkata",
    date: "2024-03-10",
    victimName: "Debashis Banerjee",
    victimContact: "+91 98300 66778",
    victimEmail: "debashis.b@calcuttaexports.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.PHISHING_DEX_ETH,
    txHash: "0xdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abc",
    cryptoType: "ETH",
    amountLost: "540000.00",
    exchangeName: "WazirX",
    telegramId: SYNDICATE_TELEGRAMS.BINANCE_CLAIM,
    websiteUrl: SYNDICATE_WEBSITES.CLAIM_AIRDROP,
    suspectMobile: SYNDICATE_MOBILES.MOB_3,
    socialMediaHandle: "twitter.com/CryptoBonusOfficial",
    ipAddress: "194.26.29.120",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim received fake email purporting to be Indian Tax Authority crypto refund.",
    status: "open",
    notes: [
      "Phishing email headers analyzed - SPF/DKIM forgery detected.",
    ],
  },
  {
    firNo: "FIR-2024-CHN-0244",
    policeStation: "Cyber Crime Cell Vepery Chennai",
    date: "2024-03-22",
    victimName: "Karthik Subramaniam",
    victimContact: "+91 94440 98123",
    victimEmail: "karthik.sub@autoancillary.co.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.PHISHING_DEX_ETH,
    txHash: "0xbcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890a",
    cryptoType: "ETH",
    amountLost: "810000.00",
    exchangeName: "CoinSwitch Kuber",
    telegramId: SYNDICATE_TELEGRAMS.BINANCE_CLAIM,
    websiteUrl: SYNDICATE_WEBSITES.CLAIM_AIRDROP,
    suspectMobile: SYNDICATE_MOBILES.MOB_3,
    socialMediaHandle: "t.me/binance_airdrop_bot_india",
    ipAddress: "194.26.29.112",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fifth linked case with Phishing Drainer ETH wallet. Total damage ₹44 Lakhs.",
    status: "escalated",
    notes: [
      "CERT-In alert requested for national firewall blocking of the phishing domain.",
    ],
  },

  // Cluster 3: Pig Butchering / Romantic Investment Fraud Bitcoin Syndicate (4 cases)
  {
    firNo: "FIR-2024-DEL-0315",
    policeStation: "Cyber Crime Cell Dwarka New Delhi",
    date: "2024-01-18",
    victimName: "Rajeev Nambiar",
    victimContact: "+91 98110 56781",
    victimEmail: "rajeev.nambiar@globalconsult.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.PIG_BUTCHERING_BTC,
    txHash: "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",
    cryptoType: "BTC",
    amountLost: "3400000.00",
    exchangeName: "Binance P2P",
    telegramId: SYNDICATE_TELEGRAMS.PIG_BUTCHERING,
    websiteUrl: SYNDICATE_WEBSITES.BITGET_PHISH,
    suspectMobile: SYNDICATE_MOBILES.MOB_4,
    socialMediaHandle: "linkedin.com/in/lucy-wealth-advisor",
    ipAddress: "185.191.171.4",
    bankDetails: "Standard Chartered Bank A/C: 42105928190, IFSC: SCBL0036001",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Classic Sha Zhu Pan (Pig Butchering) romance scam spanning 3 months before withdrawal freeze.",
    status: "under_investigation",
    notes: [
      "Scammer groomed victim over LinkedIn and WhatsApp before moving to fake Bitget exchange.",
      "BTC transactions hopped across Wasabi mixer before consolidating.",
    ],
  },
  {
    firNo: "FIR-2024-MUM-0411",
    policeStation: "Cyber Crime Cell Navi Mumbai",
    date: "2024-02-14",
    victimName: "Pooja Hegde",
    victimContact: "+91 98212 90812",
    victimEmail: "pooja.hegde@archdesign.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.PIG_BUTCHERING_BTC,
    txHash: "7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c",
    cryptoType: "BTC",
    amountLost: "2850000.00",
    exchangeName: "CoinDCX",
    telegramId: SYNDICATE_TELEGRAMS.PIG_BUTCHERING,
    websiteUrl: SYNDICATE_WEBSITES.BITGET_PHISH,
    suspectMobile: SYNDICATE_MOBILES.MOB_4,
    socialMediaHandle: "instagram.com/lucy_financial_freedom",
    ipAddress: "185.191.171.8",
    bankDetails: "HDFC Bank A/C: 50100492819283, IFSC: HDFC0000060",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim fabricated loan to invest after fake trading platform showed fake $80,000 profit.",
    status: "escalated",
    notes: [
      "Bank freeze order issued to HDFC Bank for Mule beneficiary account.",
    ],
  },
  {
    firNo: "FIR-2024-HYD-0498",
    policeStation: "Cyber Crime PS Gachibowli Hyderabad",
    date: "2024-03-01",
    victimName: "Siddharth Verma",
    victimContact: "+91 98480 33441",
    victimEmail: "siddharth.v@biopharm.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.PIG_BUTCHERING_BTC,
    txHash: "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
    cryptoType: "BTC",
    amountLost: "4200000.00",
    exchangeName: "WazirX",
    telegramId: SYNDICATE_TELEGRAMS.PIG_BUTCHERING,
    websiteUrl: SYNDICATE_WEBSITES.BITGET_PHISH,
    suspectMobile: SYNDICATE_MOBILES.MOB_4,
    socialMediaHandle: "t.me/lucy_crypto_analyst",
    ipAddress: "185.191.171.4",
    bankDetails: "Yes Bank A/C: 002391823901, IFSC: YESB0000023",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Loss of 1.15 BTC transferred directly to syndicate primary cold storage.",
    status: "under_investigation",
    notes: [
      "Wallet clustering connects to organized syndicate based in Myanmar/Cambodia SEZ hubs.",
    ],
  },
  {
    firNo: "FIR-2024-BLR-0512",
    policeStation: "Cyber Crime Cell Central Bengaluru",
    date: "2024-03-18",
    victimName: "Anand Rathi",
    victimContact: "+91 99001 87654",
    victimEmail: "anand.rathi@equityresearch.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.PIG_BUTCHERING_BTC,
    txHash: "6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f",
    cryptoType: "BTC",
    amountLost: "1900000.00",
    exchangeName: "ZebPay",
    telegramId: SYNDICATE_TELEGRAMS.PIG_BUTCHERING,
    websiteUrl: SYNDICATE_WEBSITES.BITGET_PHISH,
    suspectMobile: SYNDICATE_MOBILES.MOB_4,
    socialMediaHandle: "t.me/lucy_crypto_analyst",
    ipAddress: "185.191.171.12",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fourth linked FIR. Total BTC cluster loss stands at ₹1.23 Crores.",
    status: "open",
    notes: [
      "FIR forwarded to Special Investigation Team (SIT) Crypto Crime Unit.",
    ],
  },

  // Cluster 4: YouTube/Telegram Part-Time Task Scam Solana Syndicate (4 cases)
  {
    firNo: "FIR-2024-NOI-0112",
    policeStation: "Cyber Crime Police Station Sector 36 Noida",
    date: "2024-01-15",
    victimName: "Deepak Choudhary",
    victimContact: "+91 98188 23901",
    victimEmail: "deepak.c@noidatech.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.TASK_SCAM_SOL,
    txHash: "5KtPnPeMpkd1eE5QcZ6k3g7vQ8M4N2bK1aL9xY8uV7wT6sR5qP4oN3mK2jI1hG",
    cryptoType: "SOL",
    amountLost: "320000.00",
    exchangeName: "CoinDCX",
    telegramId: SYNDICATE_TELEGRAMS.TASK_ADMIN,
    websiteUrl: SYNDICATE_WEBSITES.TASK_EARN,
    suspectMobile: SYNDICATE_MOBILES.MOB_2,
    socialMediaHandle: "t.me/task_earning_admin_vip",
    ipAddress: "104.28.19.45",
    bankDetails: "Canara Bank A/C: 119201928391, IFSC: CNRB0001192",
    blockchainNetwork: "Solana",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim paid for rating Google Maps locations, then forced to pay 'merchant prepaid tasks'.",
    status: "under_investigation",
    notes: [
      "UPI ID task.earning@canarabank traced and frozen.",
    ],
  },
  {
    firNo: "FIR-2024-JAI-0205",
    policeStation: "Cyber Crime Police Station Jaipur City",
    date: "2024-02-01",
    victimName: "Gaurav Agarwal",
    victimContact: "+91 94140 38291",
    victimEmail: "gaurav.agarwal@marwaricap.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.TASK_SCAM_SOL,
    txHash: "2JkL9mN8bV7cE6xZ5aS4dF3gH2jK1lP0oI9uY8tR7eW6qM5nB4vC3xZ2aQ1wE0",
    cryptoType: "SOL",
    amountLost: "560000.00",
    exchangeName: "Binance",
    telegramId: SYNDICATE_TELEGRAMS.TASK_ADMIN,
    websiteUrl: SYNDICATE_WEBSITES.TASK_EARN,
    suspectMobile: SYNDICATE_MOBILES.MOB_2,
    socialMediaHandle: "whatsapp.com/channel/ReviewTaskRewards",
    ipAddress: "104.28.19.48",
    bankDetails: "Bank of Baroda A/C: 039102910293, IFSC: BARB0JAIPUR",
    blockchainNetwork: "Solana",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Second task fraud case linked to Solana wallet 9WzDXw...",
    status: "open",
    notes: [
      "Solscan cluster analysis shows continuous bridging to Raydium DEX pools.",
    ],
  },
  {
    firNo: "FIR-2024-AHD-0318",
    policeStation: "Cyber Crime Police Station Ahmedabad City",
    date: "2024-02-22",
    victimName: "Bhavin Patel",
    victimContact: "+91 98250 91823",
    victimEmail: "bhavin.patel@gujarattextiles.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.TASK_SCAM_SOL,
    txHash: "7NmK6jI5hG4fE3dC2bA1zY9xW8vU7tS6rQ5pO4nM3lK2jI1hG0fE9dC8bA7zY6",
    cryptoType: "SOL",
    amountLost: "780000.00",
    exchangeName: "WazirX",
    telegramId: SYNDICATE_TELEGRAMS.TASK_ADMIN,
    websiteUrl: SYNDICATE_WEBSITES.TASK_EARN,
    suspectMobile: SYNDICATE_MOBILES.MOB_2,
    socialMediaHandle: "t.me/task_earning_admin_vip",
    ipAddress: "104.28.19.45",
    bankDetails: "HDFC Bank A/C: 50100918239012, IFSC: HDFC0000006",
    blockchainNetwork: "Solana",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim convinced that 400 SOL deposit was required to unlock accumulated earnings.",
    status: "under_investigation",
    notes: [
      "Bank records show fund diversion into mule network across Rajasthan and Gujarat.",
    ],
  },
  {
    firNo: "FIR-2024-CHD-0410",
    policeStation: "Cyber Crime Cell Sector 17 Chandigarh",
    date: "2024-03-12",
    victimName: "Harpreet Singh",
    victimContact: "+91 98150 44321",
    victimEmail: "harpreet.singh@punjabgrain.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.TASK_SCAM_SOL,
    txHash: "4PqO3nN2mM1lK0jI9hG8fE7dC6bA5zY4xW3vU2tS1rQ0pO9nM8lK7jI6hG5fE4",
    cryptoType: "SOL",
    amountLost: "410000.00",
    exchangeName: "CoinSwitch",
    telegramId: SYNDICATE_TELEGRAMS.TASK_ADMIN,
    websiteUrl: SYNDICATE_WEBSITES.TASK_EARN,
    suspectMobile: SYNDICATE_MOBILES.MOB_2,
    socialMediaHandle: "t.me/task_earning_admin_vip",
    ipAddress: "104.28.19.50",
    blockchainNetwork: "Solana",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Linked to multi-state task scam module operating across North India.",
    status: "closed",
    notes: [
      "Accused arrested in Jaipur raid; primary recovery initiated through court order.",
    ],
  },

  // Cluster 5: BNB Chain Fake Arbitrage Bot Scheme (3 cases)
  {
    firNo: "FIR-2024-DEL-0419",
    policeStation: "Cyber Crime Cell North East Delhi",
    date: "2024-01-29",
    victimName: "Manoj Tiwari",
    victimContact: "+91 98102 99441",
    victimEmail: "manoj.tiwari@delhitraders.org",
    suspectedWalletAddress: SYNDICATE_WALLETS.ARBITRAGE_BNB,
    txHash: "0x3344556677889900aabbccddeeff11223344556677889900aabbccddeeff1122",
    cryptoType: "BNB",
    amountLost: "680000.00",
    exchangeName: "Binance",
    telegramId: SYNDICATE_TELEGRAMS.FX_TRADER,
    websiteUrl: SYNDICATE_WEBSITES.QUANT_BOT,
    suspectMobile: "+91 93100 77123",
    socialMediaHandle: "youtube.com/@DailyCryptoArbitrageIndia",
    ipAddress: "141.98.11.89",
    bankDetails: "Union Bank A/C: 39182910291, IFSC: UBIN0539182",
    blockchainNetwork: "BNB Smart Chain",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim deployed automated arbitrage bot via smart contract which transferred all BNB to owner wallet.",
    status: "under_investigation",
    notes: [
      "BscScan decompile reveals backdoored withdrawAll() function.",
    ],
  },
  {
    firNo: "FIR-2024-LKO-0215",
    policeStation: "Cyber Crime Police Station Lucknow",
    date: "2024-02-17",
    victimName: "Abhishek Srivastava",
    victimContact: "+91 94150 11223",
    victimEmail: "abhishek.sri@uptech.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.ARBITRAGE_BNB,
    txHash: "0x556677889900aabbccddeeff11223344556677889900aabbccddeeff11223344",
    cryptoType: "BNB",
    amountLost: "920000.00",
    exchangeName: "WazirX",
    telegramId: SYNDICATE_TELEGRAMS.FX_TRADER,
    websiteUrl: SYNDICATE_WEBSITES.QUANT_BOT,
    suspectMobile: "+91 93100 77123",
    socialMediaHandle: "t.me/fx_global_trader_raj",
    ipAddress: "141.98.11.89",
    bankDetails: "Kotak Mahindra Bank A/C: 7192839102, IFSC: KKBK0000142",
    blockchainNetwork: "BNB Smart Chain",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Identical smart contract deployed on BSC. ₹9.2L drained in 2 transactions.",
    status: "open",
    notes: [
      "Notices issued to YouTube India for channel takedown.",
    ],
  },
  {
    firNo: "FIR-2024-PAT-0180",
    policeStation: "Cyber Crime Police Station Patna",
    date: "2024-03-05",
    victimName: "Ramesh Kumar Singh",
    victimContact: "+91 94310 88712",
    victimEmail: "ramesh.singh@biharagro.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.ARBITRAGE_BNB,
    txHash: "0x77889900aabbccddeeff11223344556677889900aabbccddeeff112233445566",
    cryptoType: "BNB",
    amountLost: "430000.00",
    exchangeName: "CoinDCX",
    telegramId: SYNDICATE_TELEGRAMS.FX_TRADER,
    websiteUrl: SYNDICATE_WEBSITES.QUANT_BOT,
    suspectMobile: "+91 93100 77123",
    socialMediaHandle: "t.me/fx_global_trader_raj",
    ipAddress: "141.98.11.92",
    bankDetails: "Punjab National Bank A/C: 201928391823901, IFSC: PUNB0201900",
    blockchainNetwork: "BNB Smart Chain",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Third linked case with BNB Arbitrage scam cluster.",
    status: "under_investigation",
    notes: [
      "Binance compliance responded with suspected KYC identity of account beneficiary.",
    ],
  },

  // Cluster 6: Telegram VIP Pump & Dump TRC20 Syndicate (3 cases)
  {
    firNo: "FIR-2024-SUR-0155",
    policeStation: "Cyber Crime Police Station Surat City",
    date: "2024-01-22",
    victimName: "Jignesh Shah",
    victimContact: "+91 98240 55123",
    victimEmail: "jignesh.shah@suratdiamonds.com",
    suspectedWalletAddress: SYNDICATE_WALLETS.TELEGRAM_VIP_TRC20,
    txHash: "11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff",
    cryptoType: "USDT",
    amountLost: "1500000.00",
    exchangeName: "Binance P2P",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: "https://vip-signals-india.me",
    suspectMobile: "+91 98220 19283",
    socialMediaHandle: "t.me/crypto_vip_signal_in",
    ipAddress: "195.123.245.10",
    bankDetails: "IDBI Bank A/C: 01921040001928, IFSC: IBKL0000192",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim paid VIP membership fee and seed funds for insider trading pump signal.",
    status: "under_investigation",
    notes: [
      "IDBI Bank account frozen with balance of ₹8.4 Lakhs.",
    ],
  },
  {
    firNo: "FIR-2024-IND-0230",
    policeStation: "Cyber Crime Police Station Indore",
    date: "2024-02-12",
    victimName: "Nitin Jain",
    victimContact: "+91 98260 77812",
    victimEmail: "nitin.jain@indoretextiles.in",
    suspectedWalletAddress: SYNDICATE_WALLETS.TELEGRAM_VIP_TRC20,
    txHash: "3344556677889900aabbccddeeff11223344556677889900aabbccddeeff1122",
    cryptoType: "USDT",
    amountLost: "850000.00",
    exchangeName: "WazirX",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: "https://vip-signals-india.me",
    suspectMobile: "+91 98220 19283",
    socialMediaHandle: "t.me/crypto_vip_signal_in",
    ipAddress: "195.123.245.10",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Linked to Telegram VIP group scam network.",
    status: "open",
    notes: [
      "Telegram handle subpoena served through national nodal agency.",
    ],
  },
  {
    firNo: "FIR-2024-BHO-0190",
    policeStation: "Cyber Crime Police Station Bhopal",
    date: "2024-03-08",
    victimName: "Alok Saxena",
    victimContact: "+91 94250 33419",
    victimEmail: "alok.saxena@mpgovt.org",
    suspectedWalletAddress: SYNDICATE_WALLETS.TELEGRAM_VIP_TRC20,
    txHash: "556677889900aabbccddeeff11223344556677889900aabbccddeeff11223344",
    cryptoType: "USDT",
    amountLost: "620000.00",
    exchangeName: "CoinDCX",
    telegramId: SYNDICATE_TELEGRAMS.CRYPTO_VIP,
    websiteUrl: "https://vip-signals-india.me",
    suspectMobile: "+91 98220 19283",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Third complaint against VIP pump group.",
    status: "under_investigation",
    notes: [
      "Joint interrogation of mule account holder in progress.",
    ],
  },

  // Remaining Cases (Cases 26 to 50) - Diverse Individual & Regional High-Tech Frauds
  {
    firNo: "FIR-2024-DEL-0501",
    policeStation: "Cyber Crime Cell Central Delhi",
    date: "2024-01-08",
    victimName: "Tanya Kapoor",
    victimContact: "+91 98119 00123",
    victimEmail: "tanya.kapoor@fashionlabel.com",
    suspectedWalletAddress: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    txHash: "d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2",
    cryptoType: "USDT",
    amountLost: "520000.00",
    exchangeName: "WazirX",
    telegramId: "@crypto_helper_support",
    websiteUrl: "https://wazirx-support-portal.live",
    suspectMobile: "+91 98100 44556",
    socialMediaHandle: "twitter.com/WazirXSupportHelp",
    ipAddress: "103.45.12.89",
    bankDetails: "Axis Bank A/C: 919020059182391, IFSC: UTIB0000190",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Impersonation of WazirX exchange customer support executive on Twitter/X.",
    status: "under_investigation",
    notes: ["Phishing Twitter account taken down via legal notice to X."],
  },
  {
    firNo: "FIR-2024-MUM-0518",
    policeStation: "Cyber Crime Cell South Mumbai",
    date: "2024-01-14",
    victimName: "Farhan Merchant",
    victimContact: "+91 98200 77123",
    victimEmail: "farhan.merchant@shippingcargo.in",
    suspectedWalletAddress: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
    txHash: "f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3",
    cryptoType: "BTC",
    amountLost: "3800000.00",
    exchangeName: "Binance P2P",
    telegramId: "@otc_crypto_desk_mumbai",
    websiteUrl: "https://mumbai-otc-escrow.net",
    suspectMobile: "+91 98201 11223",
    socialMediaHandle: "t.me/otc_crypto_desk_mumbai",
    ipAddress: "192.178.49.20",
    bankDetails: "HDFC Bank A/C: 50100293819201, IFSC: HDFC0000019",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim attempted cash-to-crypto OTC settlement; scammer absconded post escrow transfer.",
    status: "escalated",
    notes: ["CCTV footage secured from five-star hotel lobby in Mumbai where meeting occurred."],
  },
  {
    firNo: "FIR-2024-BLR-0602",
    policeStation: "Cyber Crime Police Station Electronic City Bengaluru",
    date: "2024-01-19",
    victimName: "Venkatesh Prasad",
    victimContact: "+91 98450 66789",
    victimEmail: "venkat.prasad@semicon.com",
    suspectedWalletAddress: "0x8894E0a0c962CB723c1976a4421c95949bE2D4E3",
    txHash: "0x99aabbccddeeff11223344556677889900aabbccddeeff112233445566778899",
    cryptoType: "USDC",
    amountLost: "1150000.00",
    exchangeName: "Coinbase Cloud Phish",
    telegramId: "@web3_security_audit_bot",
    websiteUrl: "https://revoke-cash-security.cc",
    suspectMobile: "+91 99880 12345",
    socialMediaHandle: "twitter.com/RevokeCashAlerts",
    ipAddress: "185.220.101.99",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fake Revoke.cash security tool tricked victim into signing malicious transaction.",
    status: "under_investigation",
    notes: ["USDC issuer Centre/Circle contacted for potential on-chain blacklist."],
  },
  {
    firNo: "FIR-2024-HYD-0619",
    policeStation: "Cyber Crime Police Station Begumpet Hyderabad",
    date: "2024-01-26",
    victimName: "Lavanya Chunduru",
    victimContact: "+91 98491 22334",
    victimEmail: "lavanya.c@healthcorp.in",
    suspectedWalletAddress: "TW2r5K8M9nP3qL4sY7tU1vX6wZ8aB9cE2d",
    txHash: "aa11223344556677889900aabbccddeeff11223344556677889900aabbccddee",
    cryptoType: "TRX",
    amountLost: "290000.00",
    exchangeName: "CoinDCX",
    telegramId: "@tron_staking_rewards_official",
    websiteUrl: "https://tron-stake-rewards.top",
    suspectMobile: "+91 97000 88990",
    socialMediaHandle: "t.me/tron_staking_rewards_official",
    ipAddress: "103.111.45.12",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim lured into high APY staking pool on fake Tron dApp.",
    status: "open",
    notes: ["Website domain suspended following abuse report."],
  },
  {
    firNo: "FIR-2024-GGN-0630",
    policeStation: "Cyber Crime Police Station Manesar Gurugram",
    date: "2024-02-03",
    victimName: "Saurabh Jindal",
    victimContact: "+91 99100 88776",
    victimEmail: "saurabh.jindal@logistics360.com",
    suspectedWalletAddress: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
    txHash: "0x11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff",
    cryptoType: "UNI",
    amountLost: "740000.00",
    exchangeName: "Uniswap",
    telegramId: "@defi_liquidity_master",
    websiteUrl: "https://uniswap-v3-liquidity-farm.xyz",
    suspectMobile: "+91 98111 23490",
    socialMediaHandle: "reddit.com/r/CryptoDeFiIndia",
    ipAddress: "194.67.210.15",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fake DeFi yield aggregator drained UNI tokens via unlimited spend permit.",
    status: "under_investigation",
    notes: ["Smart contract bytecode matches drainer kit sold on darknet forums."],
  },
  {
    firNo: "FIR-2024-NOI-0645",
    policeStation: "Cyber Crime Police Station Sector 108 Noida",
    date: "2024-02-07",
    victimName: "Pallavi Mathur",
    victimContact: "+91 98180 55443",
    victimEmail: "pallavi.m@edutech.org",
    suspectedWalletAddress: "TKv8sL3mN2pQ1rW4tY6uX9zA8bC7dE5fG2",
    txHash: "bb223344556677889900aabbccddeeff11223344556677889900aabbccddee11",
    cryptoType: "USDT",
    amountLost: "480000.00",
    exchangeName: "Binance",
    telegramId: "@part_time_freelance_hr",
    websiteUrl: "https://data-entry-freelance.org",
    suspectMobile: "+91 98189 00987",
    socialMediaHandle: "whatsapp.com/channel/FreelanceHiring2024",
    ipAddress: "103.208.71.18",
    bankDetails: "State Bank of India A/C: 30918291029, IFSC: SBIN0004021",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim duped into paying security deposit in USDT for online translation gig.",
    status: "open",
    notes: ["SBI account under debit freeze."],
  },
  {
    firNo: "FIR-2024-PUN-0660",
    policeStation: "Cyber Crime Police Station Kothrud Pune",
    date: "2024-02-11",
    victimName: "Ajay Gokhale",
    victimContact: "+91 98220 44332",
    victimEmail: "ajay.gokhale@autocomponents.in",
    suspectedWalletAddress: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
    txHash: "0x3344556677889900aabbccddeeff11223344556677889900aabbccddeeff1122",
    cryptoType: "WBTC",
    amountLost: "2200000.00",
    exchangeName: "WazirX",
    telegramId: "@crypto_hedge_fund_india",
    websiteUrl: "https://apex-crypto-asset-management.com",
    suspectMobile: "+91 98221 55667",
    socialMediaHandle: "t.me/apex_crypto_asset_management",
    ipAddress: "185.156.73.44",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "High net worth investor promised guaranteed 25% annual return on Wrapped Bitcoin.",
    status: "under_investigation",
    notes: ["Notice issued to host provider Hetzner Online GmbH."],
  },
  {
    firNo: "FIR-2024-CHN-0675",
    policeStation: "Cyber Crime Cell Anna Nagar Chennai",
    date: "2024-02-16",
    victimName: "Sundararajan M",
    victimContact: "+91 94441 22334",
    victimEmail: "sundar.m@chennaiship.in",
    suspectedWalletAddress: "bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq",
    txHash: "cc3344556677889900aabbccddeeff11223344556677889900aabbccddee22",
    cryptoType: "BTC",
    amountLost: "1650000.00",
    exchangeName: "CoinDCX",
    telegramId: "@btc_doubler_live_2024",
    websiteUrl: "https://elon-musk-btc-giveaway.in",
    suspectMobile: "+91 94449 88776",
    socialMediaHandle: "youtube.com/live/TeslaCryptoStreamFake",
    ipAddress: "198.51.100.45",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim fell for YouTube live stream deepfake of Elon Musk offering 2x Bitcoin refund.",
    status: "closed",
    notes: ["Case closed after funds traced to foreign exchange without jurisdiction treaty."],
  },
  {
    firNo: "FIR-2024-KOL-0690",
    policeStation: "Cyber Crime PS Bidhannagar Salt Lake Kolkata",
    date: "2024-02-20",
    victimName: "Sourav Ganguly",
    victimContact: "+91 98301 99887",
    victimEmail: "sourav.ganguly@bengaltrade.org",
    suspectedWalletAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    txHash: "0x44556677889900aabbccddeeff11223344556677889900aabbccddeeff112233",
    cryptoType: "USDC",
    amountLost: "890000.00",
    exchangeName: "Binance P2P",
    telegramId: "@p2p_fast_merchant_kol",
    websiteUrl: "https://fast-p2p-escrow.org",
    suspectMobile: "+91 98300 11229",
    socialMediaHandle: "t.me/p2p_fast_merchant_kol",
    ipAddress: "103.77.192.10",
    bankDetails: "Bandhan Bank A/C: 10192839182, IFSC: BDBL0001019",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Chargeback and account freeze fraud on P2P crypto trading portal.",
    status: "under_investigation",
    notes: ["Bandhan Bank account frozen with lien of ₹5,10,000."],
  },
  {
    firNo: "FIR-2024-AHD-0705",
    policeStation: "Cyber Crime Police Station Gandhinagar",
    date: "2024-02-25",
    victimName: "Hitesh Joshi",
    victimContact: "+91 98251 33445",
    victimEmail: "hitesh.joshi@gujaratfin.com",
    suspectedWalletAddress: "TLu9vW2xY3zA4bC5dE6fG7hI8jK9lM1nO2",
    txHash: "dd44556677889900aabbccddeeff11223344556677889900aabbccddee33",
    cryptoType: "USDT",
    amountLost: "1350000.00",
    exchangeName: "ZebPay",
    telegramId: "@crypto_pms_wealth",
    websiteUrl: "https://gandhinagar-crypto-fund.in",
    suspectMobile: "+91 98259 00112",
    socialMediaHandle: "t.me/crypto_pms_wealth",
    ipAddress: "103.240.180.22",
    bankDetails: "Kotak Mahindra Bank A/C: 9019283918, IFSC: KKBK0000921",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Unregistered Portfolio Management Service promised crypto algorithmic profits.",
    status: "open",
    notes: ["SEBI and FIU-IND notifications sent for regulatory violation."],
  },
  {
    firNo: "FIR-2024-JAI-0720",
    policeStation: "Cyber Crime Police Station Vidhyadhar Nagar Jaipur",
    date: "2024-03-01",
    victimName: "Pooja Shekhawat",
    victimContact: "+91 94141 88990",
    victimEmail: "pooja.shekhawat@heritagehotels.com",
    suspectedWalletAddress: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
    txHash: "0x556677889900aabbccddeeff11223344556677889900aabbccddeeff11223344",
    cryptoType: "DAI",
    amountLost: "510000.00",
    exchangeName: "Uniswap",
    telegramId: "@defi_guru_rajasthan",
    websiteUrl: "https://maker-dao-dai-yield.cc",
    suspectMobile: "+91 94140 22334",
    socialMediaHandle: "instagram.com/crypto_pooja_trader",
    ipAddress: "182.72.10.45",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fake MakerDAO lending protocol drained DAI collateral.",
    status: "under_investigation",
    notes: ["Smart contract call graph traced on Etherscan."],
  },
  {
    firNo: "FIR-2024-CHD-0735",
    policeStation: "Cyber Crime Police Station Sector 34 Chandigarh",
    date: "2024-03-04",
    victimName: "Navneet Kaur",
    victimContact: "+91 98151 77665",
    victimEmail: "navneet.kaur@punjabinstitute.edu.in",
    suspectedWalletAddress: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    txHash: "3mN2bK1aL9xY8uV7wT6sR5qP4oN3mK2jI1hG0fE9dC8bA7zY6xW5vU4tS3rQ2pO1",
    cryptoType: "SOL",
    amountLost: "440000.00",
    exchangeName: "Phantom Wallet Phish",
    telegramId: "@solana_nft_airdrop_bot",
    websiteUrl: "https://solana-season-airdrop.vip",
    suspectMobile: "+91 98159 33221",
    socialMediaHandle: "twitter.com/SolanaAirdropClaims",
    ipAddress: "104.21.32.90",
    blockchainNetwork: "Solana",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fake NFT mint site drained SOL wallet upon connecting wallet extension.",
    status: "open",
    notes: ["Phishing site domain registrar contacted."],
  },
  {
    firNo: "FIR-2024-LKO-0750",
    policeStation: "Cyber Crime Police Station Hazratganj Lucknow",
    date: "2024-03-07",
    victimName: "Vivek Mishra",
    victimContact: "+91 94151 44556",
    victimEmail: "vivek.mishra@awadhconstructions.in",
    suspectedWalletAddress: "TN8qP2rL4sK6mY9tU1vW3xZ5aB7cE9dG1f",
    txHash: "ee556677889900aabbccddeeff11223344556677889900aabbccddee44",
    cryptoType: "USDT",
    amountLost: "980000.00",
    exchangeName: "WazirX",
    telegramId: "@crypto_lucknow_traders",
    websiteUrl: "https://up-crypto-invest.com",
    suspectMobile: "+91 94150 99881",
    socialMediaHandle: "facebook.com/groups/CryptoLucknowCommunity",
    ipAddress: "103.225.10.14",
    bankDetails: "HDFC Bank A/C: 50100381928391, IFSC: HDFC0000078",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Local WhatsApp investment scheme collecting USDT for pooled foreign trading.",
    status: "under_investigation",
    notes: ["Mastermind identified in Gomti Nagar; surveillance mounted."],
  },
  {
    firNo: "FIR-2024-PAT-0765",
    policeStation: "Cyber Crime Police Station Kankarbagh Patna",
    date: "2024-03-09",
    victimName: "Pankaj Kumar",
    victimContact: "+91 94311 00223",
    victimEmail: "pankaj.kumar@biharsteels.com",
    suspectedWalletAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    txHash: "0x6677889900aabbccddeeff11223344556677889900aabbccddeeff1122334455",
    cryptoType: "USDT",
    amountLost: "390000.00",
    exchangeName: "CoinDCX",
    telegramId: "@bihar_crypto_earning",
    websiteUrl: "https://patna-earn-crypto.top",
    suspectMobile: "+91 94310 11990",
    socialMediaHandle: "t.me/bihar_crypto_earning",
    ipAddress: "103.242.112.50",
    bankDetails: "State Bank of India A/C: 39182918239, IFSC: SBIN0001245",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Task completion scam involving crypto transfers.",
    status: "open",
    notes: ["Mule bank account frozen."],
  },
  {
    firNo: "FIR-2024-SUR-0780",
    policeStation: "Cyber Crime Police Station Adajan Surat",
    date: "2024-03-11",
    victimName: "Mehul Choksi (Victim)",
    victimContact: "+91 98241 88776",
    victimEmail: "mehul.choksi.textile@gmail.com",
    suspectedWalletAddress: "bc1q9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d",
    txHash: "ff6677889900aabbccddeeff11223344556677889900aabbccddee55",
    cryptoType: "BTC",
    amountLost: "5400000.00",
    exchangeName: "Binance",
    telegramId: "@diamond_city_crypto_otc",
    websiteUrl: "https://surat-crypto-exchange.co",
    suspectMobile: "+91 98240 33221",
    socialMediaHandle: "t.me/diamond_city_crypto_otc",
    ipAddress: "103.21.58.12",
    bankDetails: "ICICI Bank A/C: 001105928192, IFSC: ICIC0000011",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "High-value business diamond merchant duped during international crypto export settlement.",
    status: "escalated",
    notes: ["ED and FIU-IND apprised of large-scale trade-based money laundering."],
  },
  {
    firNo: "FIR-2024-IND-0795",
    policeStation: "Cyber Crime Police Station Vijay Nagar Indore",
    date: "2024-03-13",
    victimName: "Ritu Sharma",
    victimContact: "+91 98261 44332",
    victimEmail: "ritu.sharma@indorehotels.com",
    suspectedWalletAddress: "TP8sK3mL2nQ1rW4tY6uX9zA8bC7dE5fG2h",
    txHash: "0077889900aabbccddeeff11223344556677889900aabbccddee66",
    cryptoType: "USDT",
    amountLost: "670000.00",
    exchangeName: "WazirX",
    telegramId: "@indore_part_time_work",
    websiteUrl: "https://hotel-review-crypto.biz",
    suspectMobile: "+91 98260 99112",
    socialMediaHandle: "t.me/indore_part_time_work",
    ipAddress: "103.88.23.19",
    bankDetails: "Axis Bank A/C: 918020089182390, IFSC: UTIB0000182",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Hotel booking review rating scam on Telegram.",
    status: "under_investigation",
    notes: ["Axis Bank account frozen."],
  },
  {
    firNo: "FIR-2024-BHO-0810",
    policeStation: "Cyber Crime Police Station MP Nagar Bhopal",
    date: "2024-03-14",
    victimName: "Sanjay Dixit",
    victimContact: "+91 94251 99001",
    victimEmail: "sanjay.dixit@mpenergy.gov.in",
    suspectedWalletAddress: "0x4Fabb145d64652a948d72533023f6E7A623C7C53",
    txHash: "0x77889900aabbccddeeff11223344556677889900aabbccddeeff112233445566",
    cryptoType: "BUSD",
    amountLost: "820000.00",
    exchangeName: "Binance",
    telegramId: "@busd_yield_farm_india",
    websiteUrl: "https://busd-rewards-claim.org",
    suspectMobile: "+91 94250 11992",
    socialMediaHandle: "twitter.com/BUSDYieldFarms",
    ipAddress: "185.220.102.14",
    blockchainNetwork: "BNB Smart Chain",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Phishing dApp drained BUSD and BNB balance from TrustWallet.",
    status: "open",
    notes: ["Wallet flagged on BSC explorer."],
  },
  {
    firNo: "FIR-2024-DEL-0825",
    policeStation: "Cyber Crime Cell Rohini Delhi",
    date: "2024-03-16",
    victimName: "Amit Aggarwal",
    victimContact: "+91 98112 88990",
    victimEmail: "amit.aggarwal@rohinicomp.in",
    suspectedWalletAddress: "TQ9sK4mL3nP2rW5tY7uX0zA9bC8dE6fG3i",
    txHash: "11889900aabbccddeeff11223344556677889900aabbccddee77",
    cryptoType: "USDT",
    amountLost: "1100000.00",
    exchangeName: "CoinDCX",
    telegramId: "@rohini_crypto_club",
    websiteUrl: "https://delhi-crypto-club.vip",
    suspectMobile: "+91 98110 99441",
    socialMediaHandle: "t.me/rohini_crypto_club",
    ipAddress: "103.14.120.44",
    bankDetails: "Punjab National Bank A/C: 102910291029102, IFSC: PUNB0102900",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fake community trading club collected funds promising 15% monthly compounding.",
    status: "under_investigation",
    notes: ["Two local suspects detained for questioning."],
  },
  {
    firNo: "FIR-2024-MUM-0840",
    policeStation: "Cyber Crime Cell Andheri Mumbai",
    date: "2024-03-17",
    victimName: "Natasha Fernandes",
    victimContact: "+91 98202 33441",
    victimEmail: "natasha.f@goahospitality.com",
    suspectedWalletAddress: "0x514910771AF9Ca656af840dff83E8264EcF986CA",
    txHash: "0x889900aabbccddeeff11223344556677889900aabbccddeeff11223344556677",
    cryptoType: "LINK",
    amountLost: "930000.00",
    exchangeName: "Kraken",
    telegramId: "@chainlink_node_rewards",
    websiteUrl: "https://chainlink-node-staking.io",
    suspectMobile: "+91 98200 44551",
    socialMediaHandle: "twitter.com/LinkNodeRewardsFake",
    ipAddress: "194.26.29.99",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim deposited LINK tokens into fake Chainlink node validator staking pool.",
    status: "open",
    notes: ["Smart contract funds moved to KuCoin deposit address."],
  },
  {
    firNo: "FIR-2024-BLR-0855",
    policeStation: "Cyber Crime Police Station Koramangala Bengaluru",
    date: "2024-03-19",
    victimName: "Girish Murthy",
    victimContact: "+91 98451 99887",
    victimEmail: "girish.murthy@bangaloreai.com",
    suspectedWalletAddress: "EQDk28Hp14P14DTnmXdYVicbY09vdS1AZNqpvRnvUjhZPWsp",
    txHash: "229900aabbccddeeff11223344556677889900aabbccddee88",
    cryptoType: "TON",
    amountLost: "750000.00",
    exchangeName: "OKX",
    telegramId: "@ton_notcoin_mining_bot",
    websiteUrl: "https://notcoin-mining-vip.org",
    suspectMobile: "+91 98450 11992",
    socialMediaHandle: "t.me/ton_notcoin_mining_bot",
    ipAddress: "185.191.171.88",
    blockchainNetwork: "TON",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Telegram mini-app clicker game scam drained TON wallet through malicious jetton transfer.",
    status: "under_investigation",
    notes: ["Tonkeeper wallet security team notified."],
  },
  {
    firNo: "FIR-2024-HYD-0870",
    policeStation: "Cyber Crime Police Station Madhapur Hyderabad",
    date: "2024-03-20",
    victimName: "Harish Varma",
    victimContact: "+91 98492 11223",
    victimEmail: "harish.varma@hitechpharma.in",
    suspectedWalletAddress: "TR8sK5mL4nP3rW6tY8uX1zA0bC9dE7fG4j",
    txHash: "330011223344556677889900aabbccddee99",
    cryptoType: "USDT",
    amountLost: "1850000.00",
    exchangeName: "Binance",
    telegramId: "@hyderabad_crypto_realestate",
    websiteUrl: "https://dubai-property-crypto.net",
    suspectMobile: "+91 98490 88991",
    socialMediaHandle: "instagram.com/dubai_crypto_property_realtor",
    ipAddress: "103.212.43.99",
    bankDetails: "HDFC Bank A/C: 50100481928391, IFSC: HDFC0000128",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Scammer posed as Dubai real estate agent accepting USDT for booking token payment.",
    status: "escalated",
    notes: ["Interpol red corner request considered for fugitive suspect."],
  },
  {
    firNo: "FIR-2024-GGN-0885",
    policeStation: "Cyber Crime Police Station DLF Phase 1 Gurugram",
    date: "2024-03-21",
    victimName: "Sameer Saxena",
    victimContact: "+91 99101 22990",
    victimEmail: "sameer.saxena@gurgaonlaw.in",
    suspectedWalletAddress: "0x1111111254EEB25477B68fb85Ed929f73A960582",
    txHash: "0x990011223344556677889900aabbccddeeff11223344556677889900aabbccdd",
    cryptoType: "1INCH",
    amountLost: "580000.00",
    exchangeName: "1inch Network Clone",
    telegramId: "@oneinch_dex_aggregator_bot",
    websiteUrl: "https://1inch-token-swap.xyz",
    suspectMobile: "+91 99100 44332",
    socialMediaHandle: "t.me/oneinch_dex_aggregator_bot",
    ipAddress: "194.26.29.88",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim used cloned 1inch router contract that skimmed 100% of swapped tokens.",
    status: "under_investigation",
    notes: ["DNS sinkholing initiated for malicious domain."],
  },
  {
    firNo: "FIR-2024-NOI-0900",
    policeStation: "Cyber Crime Police Station Sector 62 Noida",
    date: "2024-03-23",
    victimName: "Rashmi Bhatnagar",
    victimContact: "+91 98181 77665",
    victimEmail: "rashmi.b@noidaschools.edu.in",
    suspectedWalletAddress: "TS9tL6mN5pQ4rW7uY9vX2zB1cD0eF8gH5k",
    txHash: "4411223344556677889900aabbccddee00",
    cryptoType: "USDT",
    amountLost: "340000.00",
    exchangeName: "CoinDCX",
    telegramId: "@amazon_gift_card_crypto",
    websiteUrl: "https://amazon-crypto-cashback.top",
    suspectMobile: "+91 98180 11223",
    socialMediaHandle: "whatsapp.com/channel/AmazonVoucherDeals",
    ipAddress: "103.111.45.99",
    bankDetails: "State Bank of India A/C: 38192839182, IFSC: SBIN0006012",
    blockchainNetwork: "Tron TRC-20",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Fake Amazon gift card cashback scheme in crypto.",
    status: "closed",
    notes: ["Full refund recovered from mule account and returned to victim under court order."],
  },
  {
    firNo: "FIR-2024-PUN-0915",
    policeStation: "Cyber Crime Police Station Hinjewadi Pune",
    date: "2024-03-24",
    victimName: "Shashank Joshi",
    victimContact: "+91 98221 00998",
    victimEmail: "shashank.joshi@hinjewaditech.com",
    suspectedWalletAddress: "bc1qxy9876543210abcdef9876543210abcdef98",
    txHash: "55223344556677889900aabbccddee11",
    cryptoType: "BTC",
    amountLost: "2750000.00",
    exchangeName: "Binance",
    telegramId: "@ransom_decrypt_support_2024",
    websiteUrl: "https://lockbit-decrypt-recovery.onion",
    suspectMobile: "+91 98220 77665",
    socialMediaHandle: "twitter.com/RansomwareDecryptPro",
    ipAddress: "185.220.101.4",
    blockchainNetwork: "Bitcoin",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Ransomware extortion payment made by IT firm to recover encrypted cloud databases.",
    status: "under_investigation",
    notes: ["Incident response report filed; ransomware strain identified as LockBit 3.0 variant."],
  },
  {
    firNo: "FIR-2024-DEL-0930",
    policeStation: "Cyber Crime Cell South West Delhi",
    date: "2024-03-24",
    victimName: "Kavita Singhal",
    victimContact: "+91 98113 44556",
    victimEmail: "kavita.singhal@delhiuniversity.ac.in",
    suspectedWalletAddress: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
    txHash: "0xaa11223344556677889900aabbccddeeff11223344556677889900aabbccddee",
    cryptoType: "ETH",
    amountLost: "670000.00",
    exchangeName: "WazirX",
    telegramId: "@ai_trading_signals_delhi",
    websiteUrl: "https://ai-trading-matrix-delhi.cc",
    suspectMobile: "+91 98110 33221",
    socialMediaHandle: "t.me/ai_trading_signals_delhi",
    ipAddress: "103.45.12.99",
    blockchainNetwork: "Ethereum",
    screenshotsCollected: true,
    evidenceAttached: true,
    remarks: "Victim purchased fraudulent AI algorithmic bot subscription with ETH.",
    status: "open",
    notes: ["Domain hosted on Cloudflare; notice sent under Section 91 CrPC."],
  },
];

async function seed() {
  console.log("[Seed] Ensuring tables...");
  await initDb();

  console.log("[Seed] Seeding officers...");
  await db.insert(officersTable).values([
    { userId: "yatharth", passwordHash: "yatharth123", name: "Admin Officer", designation: "Admin", badgeNo: "ADM001", policeStation: "Cyber Crime HQ" },
    { userId: "officer001", passwordHash: "Pass@1234", name: "Rajesh Kumar", designation: "Inspector", badgeNo: "INS001", policeStation: "Cyber Crime Cell Delhi" },
    { userId: "officer002", passwordHash: "Pass@1234", name: "Priya Sharma", designation: "Sub-Inspector", badgeNo: "SI002", policeStation: "Cyber Crime Cell Mumbai" },
    { userId: "officer003", passwordHash: "Pass@1234", name: "Vikramaditya Singh", designation: "Deputy SP", badgeNo: "DSP003", policeStation: "Cyber Crime Cell Bengaluru" },
    { userId: "officer004", passwordHash: "Pass@1234", name: "Ananya Iyer", designation: "Inspector", badgeNo: "INS004", policeStation: "Cyber Crime Cell Cyberabad" },
  ]).onConflictDoNothing();

  console.log(`[Seed] Inserting ${dummyCases.length} cases...`);

  // Clear existing dummy data if needed or insert with conflict check
  for (const c of dummyCases) {
    const existing = await db.select().from(casesTable).where(eq(casesTable.firNo, c.firNo));
    let caseId: number;

    if (existing.length === 0) {
      const [inserted] = await db.insert(casesTable).values({
        firNo: c.firNo,
        policeStation: c.policeStation,
        date: c.date,
        victimName: c.victimName,
        victimContact: c.victimContact,
        victimEmail: c.victimEmail,
        suspectedWalletAddress: c.suspectedWalletAddress,
        txHash: c.txHash,
        cryptoType: c.cryptoType,
        amountLost: c.amountLost,
        exchangeName: c.exchangeName,
        telegramId: c.telegramId ?? null,
        websiteUrl: c.websiteUrl ?? null,
        suspectMobile: c.suspectMobile ?? null,
        socialMediaHandle: c.socialMediaHandle ?? null,
        ipAddress: c.ipAddress ?? null,
        bankDetails: c.bankDetails ?? null,
        blockchainNetwork: c.blockchainNetwork,
        screenshotsCollected: c.screenshotsCollected,
        evidenceAttached: c.evidenceAttached,
        remarks: c.remarks,
        status: c.status,
        riskLevel: "low",
        linkedCaseCount: 0,
      }).returning();
      caseId = inserted.id;
    } else {
      caseId = existing[0].id;
    }

    // Insert notes if available
    if (c.notes && c.notes.length > 0) {
      for (const noteContent of c.notes) {
        await db.insert(investigationNotesTable).values({
          caseId,
          officerId: 1,
          content: noteContent,
          noteType: "investigation",
        }).onConflictDoNothing();
      }
    }
  }

  console.log("[Seed] Calculating link matches, risk levels, and alerts across all cases...");

  const allCases = await db.select().from(casesTable);

  for (const c of allCases) {
    // Find all matching cases (same wallet, telegram, mobile, website)
    const matches = allCases.filter(other => 
      other.id !== c.id && (
        (c.suspectedWalletAddress && other.suspectedWalletAddress === c.suspectedWalletAddress) ||
        (c.telegramId && other.telegramId && other.telegramId === c.telegramId) ||
        (c.suspectMobile && other.suspectMobile && other.suspectMobile === c.suspectMobile) ||
        (c.websiteUrl && other.websiteUrl && other.websiteUrl === c.websiteUrl)
      )
    );

    const walletMatches = matches.filter(other => c.suspectedWalletAddress && other.suspectedWalletAddress === c.suspectedWalletAddress);
    const telegramMatches = matches.filter(other => c.telegramId && other.telegramId && other.telegramId === c.telegramId);
    const mobileMatches = matches.filter(other => c.suspectMobile && other.suspectMobile && other.suspectMobile === c.suspectMobile);
    const websiteMatches = matches.filter(other => c.websiteUrl && other.websiteUrl && other.websiteUrl === c.websiteUrl);

    const linkedCount = matches.length;
    let riskLevel = "low";
    if (linkedCount >= 5) riskLevel = "critical";
    else if (linkedCount >= 3) riskLevel = "high";
    else if (linkedCount >= 1) riskLevel = "medium";

    await db.update(casesTable)
      .set({ riskLevel, linkedCaseCount: linkedCount })
      .where(eq(casesTable.id, c.id));

    // Generate alerts if not already created
    if (walletMatches.length > 0) {
      await db.insert(alertsTable).values({
        type: "wallet_match",
        message: `High-risk wallet ${c.suspectedWalletAddress.slice(0, 10)}... matched across ${walletMatches.length} other FIR(s). Case: ${c.firNo}`,
        severity: walletMatches.length >= 3 ? "critical" : "warning",
        caseId: c.id,
        firNo: c.firNo,
        isRead: false,
      }).onConflictDoNothing();
    }

    if (telegramMatches.length > 0) {
      await db.insert(alertsTable).values({
        type: "telegram_match",
        message: `Suspect Telegram "${c.telegramId}" linked to ${telegramMatches.length} other complaint(s). FIR: ${c.firNo}`,
        severity: "warning",
        caseId: c.id,
        firNo: c.firNo,
        isRead: false,
      }).onConflictDoNothing();
    }

    if (mobileMatches.length > 0) {
      await db.insert(alertsTable).values({
        type: "mobile_match",
        message: `Suspect mobile ${c.suspectMobile} linked with ${mobileMatches.length} registered FIR(s). Case: ${c.firNo}`,
        severity: "warning",
        caseId: c.id,
        firNo: c.firNo,
        isRead: false,
      }).onConflictDoNothing();
    }

    if (websiteMatches.length > 0) {
      await db.insert(alertsTable).values({
        type: "website_match",
        message: `Fraudulent URL ${c.websiteUrl} detected in ${websiteMatches.length} other case(s). FIR: ${c.firNo}`,
        severity: "warning",
        caseId: c.id,
        firNo: c.firNo,
        isRead: false,
      }).onConflictDoNothing();
    }
  }

  console.log(`[Seed] Successfully seeded 50 comprehensive cases and intelligence links!`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("[Seed] Error executing seed:", err);
  process.exit(1);
});